class Opcion(enumerate):
    RECIBIR_DINERO = 1
    ENVIAR_DINERO = 2
    MOSTRAR_VALANCE_GENERAL = 3
    MOSTRAR_VALANCE_MONEDA = 4
    MOSTRAR_HISTORIAL_TRANSACCIONES = 5
    SALIR = 6
    MOSTRAR_USUARIOS = 7